### PR TITLE
feat(VETS-CPC-1389): refactor workhours json

### PR DESCRIPTION
**Pull request by Apoleh**
**JIRA:** link to jira ticket
https://champlainsaintlambert.atlassian.net/browse/CPC-1389
## Context:
Work hours are now displayed in a clear calendar format instead of a confusing string representation.
## Does this PR change the .vscode folder in petclinic-frontend?:
No

<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes

- Implemented a calendar format for displaying work hours, improving clarity and usability.
- Merged consecutive hour ranges for a more concise representation.

## Before and After UI (Required for UI-impacting PRs)
Before:
image

After:
image

### CODE REVIEW

**Review by bluement — DISMISSED** [review]
looks good low ammount of files changed and frontend looks clean, well done

**Review by kyrusho — COMMENTED** [review]
Nice job! Just remove the extra comments on the code and then it will be good to go.

**Review by kyrusho — APPROVED** [review]
Good work.

**Review by bluement — APPROVED** [review]
again, looks good no life threatening changes and frontend looks clean, well done

**Pull request merged**
