### PR TITLE
conf(VISE-CPC-282): Configuring Lombok to ignore auto generated methods for Jacoco

### PR DESCRIPTION
**Pull request by bthorng**
* Changed the minimum code coverage to 90% in build.gradle
* Added a new file called lombok.config that has a configuration for Lombok to add a generated annotation to generated methods which will be ignored for testing code coverage by Jacoco
* Added missing tests to bring code coverage to 100%

This shouldn't break main.
All that's left is for @lbains to merge his fix for his PUT mapping (CPC-212) and the code coverage will become 100%. (It's 98% without his fix)

### CODE REVIEW

**Review by lbains — APPROVED** [review]
- Good changes made to the tests

**Review by cjayneb — APPROVED** [review]
We will have to remove one of the methods that return visits for a single pet in VisitResource since it is redundant. But other than that, LGTM!

**Review by cjayneb — APPROVED** [review]
LGTM!

**Review by cjayneb — APPROVED** [review]
LGTM

**Review by cjayneb — APPROVED** [review]
LGTM

**Review by lbains — APPROVED** [review]
LGTM

**Pull request merged**
