### PR TITLE
Feat(VETS-CPC-231): Front-End Data Validation

### PR DESCRIPTION
**Pull request by Louenes099**
Did the maximum of Data Validation possible within the front-end (vet-form.html).

Limited verification is doable with AngularJS.

Back-End verification covers more ground for the data clean/verification.

### CODE REVIEW

**Comment by Louenes099** [comment]
Everything works

**Comment by Louenes099** [comment]
Front-End data validation was halfway added when the form was created

**Comment by Louenes099** [comment]
image
image
image

Proof of everything working

**Review by SmoothWin — CHANGES_REQUESTED** [review]
you have commited changes I see but we need examples of the implementation or logic sketch / diagram in order to show what your implementations did.

Would like you to add these to the pull request

**Comment by Louenes099** [comment]
image

This image shows an input field for firstName with the requirements. The span is shown when the fields are improperly filled after the form submit button is clicked and the logic is being taken from the JS file. Right now it isn't working as the form is independent in its own way right now as it is missing components from the API-Gateway team.

**Comment by Louenes099** [comment]
The previous comment still applies after the changes

**Comment by Louenes099** [comment]
image
image
image
image

All necessary proof of the application running after changes

**Review by SmoothWin — DISMISSED** [review]

**Review by SmoothWin — CHANGES_REQUESTED** [review]
What is with you throwing exceptions inside the catch block
shouldn't they be thrown inside the try block.
change this please.

**Comment by SmoothWin** [comment]
Never mind the first line comment u can keep the one in the catch block.
But in order for you to reach that catch block you will need to manually throw an exception of type HttpClientErrorException inside the try block in order to then to reach the catch block and reach your catch block or else it will never reach that block

**Comment by Louenes099** [comment]
image
image

**Comment by Louenes099** [comment]
image
image

Proof of everything working in terms of deploying and usage. Missing APIG's work to plug the submit button to the service so that all the input data be saved in the database.

**Review by Chloedunwoody — APPROVED** [review]
clean and functional, see no issues.

**Review by JordanAlbayrak — APPROVED** [review]
From what I can tell, everything seems fine. I approve it.

**Pull request merged**
