### PR TITLE
feat(CSTM-CPC-900) Error Handling for Owners

### PR DESCRIPTION
**Pull request by mattjulienn**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-900?atlOrigin=eyJpIjoiMTUxZTEyYTZiMzI2NDAyZThkZDA2YzAyN2Y3YWQ0MDciLCJwIjoiaiJ9

## Context:

This story was simply to make the field requisites stricter for Owners. Before, we could input as big as big of a first name as we wished, for example. This may impose a security or reliability risk, so after consulting with the POs, We concurred at 50 characters for the limit. We could also input emojis which will just cause issues in a real life project. Foreign characters aren't accepted anymore since only ASCII characters are accepted. If a user submits a form with unacceptable fields, it will warn the user via a dialogue box that they must respect the ASCII formatting rule.

## Changes

ADDED 50 character maximum to all form fields for Register and Edit Owner
ADDED ASCII only text to all form fields for Register and Edit Owner
FIXED Grammar

## Before and After UI

BEFORE (See large fields, emojis, invalid formats, etc)
image

AFTER (Uniform information, less possibility of errors down the line, etc)
image

### CODE REVIEW

**Review by Nmazza1 — APPROVED** [review]
Sad I can't put emoji's anymore but a necessary change. The Max length may be an issue if someone has a long name

**Comment by mattjulienn** [comment]
> Sad I can't put emoji's anymore but a necessary change. The Max length may be an issue if someone has a long name

name 1 human with 50 characters in their first or last name

**Comment by Nmazza1** [comment]
> > Sad I can't put emoji's anymore but a necessary change. The Max length may be an issue if someone has a long name
> 
> name 1 human with 50 characters in their first or last name

According the Guinness World Records, this persons name is 700+ Characters. We don't want our system to discriminate someone based off the length of their name.

Adolph Blaine Charles David Earl Frederick Gerald Hubert Irvin John Kenneth Lloyd Martin Nero Oliver Paul Quincy Randolph Sherman Thomas Uncas Victor William Xerxes Yancy Zeus Wolfeschlegelsteinhausenbergerdorffwelchevoralternwarengewissenhaftschaferswessenschafewarenwohlgepflegeundsorgfaltigkeitbeschutzenvonangreifendurchihrraubgierigfeindewelchevoralternzwolftausendjahresvorandieerscheinenvanderersteerdemenschderraumschiffgebrauchlichtalsseinursprungvonkraftgestartseinlangefahrthinzwischensternartigraumaufdersuchenachdiesternwelchegehabtbewohnbarplanetenkreisedrehensichundwohinderneurassevonverstandigmenschlichkeitkonntefortpflanzenundsicherfreuenanlebenslanglichfreudeundruhemitnichteinfurchtvorangreifenvonandererintelligentgeschopfsvonhinzwischensternartigraum.

**Review by dazhuox — APPROVED** [review]
Looks great, I would suggest thinking about having a way for owners to hold more than just the address and the city, maybe add province/state as well.

**Comment by mattjulienn** [comment]
> Looks great, I would suggest thinking about having a way for owners to hold more than just the address and the city, maybe add province/state as well.

Good suggestion. i'll see what i can do in proceeding stories, family

**Pull request merged**
