### PR TITLE
Feat/invt cpc 1052 fix edit item

### PR DESCRIPTION
**Pull request by Sunveerg**
Added the edit inventory button that shows a form pre-populated with the information on the inventory you are trying to edit. The information is only edited on the front end for now.

JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1052

# Context
The edit button redirected you to an unknown page

# Changes
Added a form you can fill out to edit an inventory

# Dev notes (Optional)
Please verify this pull request

### CODE REVIEW

**Review by Carlos-123321 — APPROVED** [review]
LGTM

**Review by igouriny — COMMENTED** [review]
Looks good

**Review by igouriny — APPROVED** [review]
Looks good to me

**Comment by cgerard321** [comment]
Where are your screenshots? It doesn't look like you filled up the form very well.

**Pull request merged**
