### PR TITLE
Feat(VETS-CPC-229): Error Handling

### PR DESCRIPTION
**Pull request by Louenes099**
Created Error Handling Methods for the Vets Service.
Changed old backend code verification and clean up methods to throw exceptions if there are bad values encountered

### CODE REVIEW

**Review by Iana-Sha — DISMISSED** [review]
Looks good. Good job!

**Review by SmoothWin — CHANGES_REQUESTED** [review]
Remove the files from the .vs folder because they shouldnt be there add them to the .gitignore

**Comment by Louenes099** [comment]
image

**Comment by Louenes099** [comment]
image

**Comment by Louenes099** [comment]
Docker can't be build because of an error in go:
image

**Comment by Louenes099** [comment]
Successfully runs after patch updated by Nariman
image

**Review by Iana-Sha — APPROVED** [review]
Looks awesome!
Good job;)

**Review by SmoothWin — APPROVED** [review]
Pull request files and application run proof are satisfactory and the .gitignore was modified accordingly

**Pull request merged**
