### PR TITLE
Feat/vets cpc 1074 get vet by vet Id 

### PR DESCRIPTION
**Pull request by hristoiv11**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1074

Context:
By clicking on the veterinarian's name in the "Veterinarians" tab, it brings you to the veterinarian details page.

Changes
Created the VetDetails page which can be accessed by valid vetId and gives information about the veterinarian.
Created a VetController in the v2 folder inside the api-gateway and created my method.
Created tests for the "VetControllerIntegrationTest" inside the api-gateway.
Fixed tests inside the vet-service.

BEFORE: it was a blank page, and you couldn't access the VetDetails page with Id
AFTER:
image
image
image
image

### CODE REVIEW

**Review by Apoleh — DISMISSED** [review]
Get by id looks well implemented and front end and back end. nice

**Review by Zako563 — APPROVED** [review]
does not affect other service and it works

**Review by Apoleh — DISMISSED** [review]
good changes well done

**Review by vinivelozo — DISMISSED** [review]
Good changes. Looks good

**Pull request closed without merging**
