### PR TITLE
feat/(CUST-CPC-1148): Improve UI/UX for users when navigating and accessing features

### PR DESCRIPTION
**Pull request by flyindonut**
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1148
## Context:
Currently a lot of pages aren't routed properly, sometimes when logging in it redirects to a blank page, logging out actually doesn't work properly, etc. These issues will make the experience of a user of the Champlain Pet Clinic miserable.
## Does this PR change the .vscode folder in petclinic-frontend?:
No
## Changes
- Improved the navigation bar. It will now render differently for users depending on their roles. A customer will not see the inventories in the navigation bar, an inventory manager will not see the visits in the navigation bar, etc.
- The navbar is now responsive. It will work on a smaller screen.
- There is now a dropdown menu for the user. The dropdown menu is different based on roles.
- Routed all pages properly. Made the home page accessible to users that are not logged in.
- Improved the home page.
- "/" will now redirect to "/home" (home page)
- Users can actually log out now.

## Before and After UI (Required for UI-impacting PRs)
**Before**
Home page
image
Home page small screen
image
**After**
Guest view of home page
image
Admin view of home page (different navbar and user menu)
image
Customer view of home page (different navbar and user menu)
image
Smaller screen
image
Smaller screen + menu
image

### CODE REVIEW

**Review by AndrewBadIdea — APPROVED** [review]

**Review by AndrewBadIdea — APPROVED** [review]

**Review by NotZagreus — COMMENTED** [review]
Wow, looks amazing, imma have a merge conflict here but its alright

**Review by NotZagreus — APPROVED** [review]
Looks great!

**Comment by viktorkuts** [comment]
Logout doesn't seem to work: it returns you to home page and when you go back to home, you can see that you are still signed in. I can see that you have a function that deletes something from localStorage, but I think you need to remove the Bearer cookie too.

**Comment by flyindonut** [comment]
> Logout doesn't seem to work: it returns you to home page and when you go back to home, you can see that you are still signed in. I can see that you have a function that deletes something from localStorage, but I think you need to remove the Bearer cookie too.

That's weird, the post request should be successful and delete the cookie. When I tested, the user was successfully logged out in the log of the API gateway. I'll check again when I can.

**Comment by flyindonut** [comment]
> Logout doesn't seem to work: it returns you to home page and when you go back to home, you can see that you are still signed in. I can see that you have a function that deletes something from localStorage, but I think you need to remove the Bearer cookie too.

So I logged in as a customer, edited my profile, and logged out. Here are the logs:
image
Then I went to the home page and that's how it looks like:
image
This was done on my local main branch which is up-to-date with origin/main. Could you check again?

**Pull request merged**
