### PR TITLE
feat(VIST-1212): Implement A Reminder Email (#420)

### PR DESCRIPTION
**Pull request by FelixAllard**
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1212)
## Context:
We want to be able to send email with a delay. This way you can send it not instantly
## Does this PR change the .vscode folder in petclinic-frontend?:
No
## Changes
I added some tests to the Api gateway, added a new endpoint to api gateway, added 76 test to the emailing service and implemented a new service inside the Emailing service which sends message at the time needed
## Before and After UI (Required for UI-impacting PRs)
No UI

### CODE REVIEW

**Comment by ioannisp03** [comment]
Hey! Would you mind adding a context? 
I see this right now: "Context: What is the ticket about and why are we doing this change."

**Comment by FelixAllard** [comment]
Thank you for the comment!

**Review by ioannisp03 — APPROVED** [review]
All tests, pass. Nothing looks wrong in the PR

**Review by Rrregine — APPROVED** [review]
Only your own emailing service is modified, this is very good! 

A lot of tests are implemented, and they all pass. Thanks for your hardworking!

**Pull request merged**
