### PR TITLE
Fixed UpdateOwnerByOwnerIdTest

### PR DESCRIPTION
**Pull request by Saimirz**
https://champlainsaintlambert.atlassian.net/browse/CPC-960?atlOrigin=eyJpIjoiOTRjZWI1MjQ3NTYxNDE5NjkxNTUxNWEwMGZlYTRlMzEiLCJwIjoiaiJ9## 
Context:
This is a ownerControllerIntegration test which was failing and that needed to be fixed.
## Changes
I changed the test format and used the public Owner Id
## Before and After UI (Required for UI-impacting PRs)
If this is a change to the UI, include before and after screenshots to show the differences.
If this is a new UI feature, include screenshots to show reviewers what it looks like. 
## Dev notes (Optional)
- Specific technical changes that should be noted
## Linked pull requests (Optional)
- pull request link

### CODE REVIEW

**Review by Nmazza1 — APPROVED** [review]
Did you ever figure out the root cause of the problem?

**Review by DisgruntledMensch — DISMISSED** [review]
Looks good brah

**Review by DisgruntledMensch — APPROVED** [review]
All good

**Review by Nmazza1 — APPROVED** [review]
👍

**Pull request merged**
