### PR TITLE
bug(CSTM-859) Make Api Gateway Accept Pet Requests

### PR DESCRIPTION
**Pull request by Nmazza1**
Made it so CustomerService client now accepts pet and owner requests and not only pets

JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-859?atlOrigin=eyJpIjoiMDMwMmNlNzQ5MjcxNDdhMzk0ZDAwZWUyYTU3MGE0MzAiLCJwIjoiaiJ9)
## Context:
CustomersServiceReactive only accepted Owner Requests
## Changes
Requests can be made to Pets and Owners now and not only Owners.
Allows for easier data manipulation
## Dev notes (Optional)
RAAAAAAAAAAAAAAAAAAAAA

### CODE REVIEW

**Review by 1-emil — APPROVED** [review]

**Review by DisgruntledMensch — APPROVED** [review]
Looks to be working

**Comment by 1-emil** [comment]
Looking good

**Comment by 1-emil** [comment]
Good but test don't work but I need the code for my stuff to work

**Review by 1-emil — APPROVED** [review]
Testing works nice

**Review by DisgruntledMensch — APPROVED** [review]
Tests passed, looks good this time sport

**Comment by Nmazza1** [comment]
Accidentally invited the wrong people for code review MY BAD 😨

**Review by Iantomasi — APPROVED** [review]
Looks like it could potentially fix common issues in the api-gateway. Passes the vibe check.

**Pull request merged**
