### PR TITLE
conf/CART-CPC-1088_Initialize_Cart_Service

### PR DESCRIPTION
**Pull request by mzolovska**
Created the cart service

JIRA: (https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1088)
## Context:
Created the cart service for further use for my team
## Changes
Added a new service, changed the docket-compose.yml by adding the service
## Dev notes (Optional)
Try if it builds on your side

### CODE REVIEW

**Comment by cgerard321** [comment]
Your project is still not included in the build. You forgot to add it to the settings.gradle in the root folder.

**Comment by cgerard321** [comment]
Also, the package name is com.example when it should be com.petclinic.cartsservice

**Review by cgerard321 — APPROVED** [review]
The ./gradlew build, docker compose build and up seem to work. 
However, the build.gradle is very bare bones (no lombok, no jacoco, no test configuration). There are also no packages for presentation, business, dataaccess layers. 
Why am I mentioning this? Because every team member will need to add/update these items on their own branches, which will very likely lead to many merge conflicts. 

Personally, I would add them in this PR, but that's up to you guys. :)

**Review by viktorkuts — DISMISSED** [review]
Looks good to me

**Review by viktorkuts — DISMISSED** [review]
Fixed merge conflict in docker-compose.yml for you, should be good now

**Review by viktorkuts — APPROVED** [review]
Tested, good for merge
image

**Review by Valthefirst — CHANGES_REQUESTED** [review]
When runing" **./gradle clean build test** " there is a test in the visits-service-new that fails. It's in the VisitsControllerIntegrationTest class and the name of the test is getAllVisits() method. It fails because there's an assertion failure. It expected 5 but it received 4

**Comment by viktorkuts** [comment]
> When runing" **./gradle clean build test** " there is a test in the visits-service-new that fails. It's in the VisitsControllerIntegrationTest class and the name of the test is getAllVisits() method. It fails because there's an assertion failure. It expected 5 but it received 4

This issue is unrelated to this PR, as it's already in main. When running gradle clean build test on directory where changes were made (cart-service), everything passes, so it's not these changes that are of cause.

**Comment by Valthefirst** [comment]
> > When runing" **./gradle clean build test** " there is a test in the visits-service-new that fails. It's in the VisitsControllerIntegrationTest class and the name of the test is getAllVisits() method. It fails because there's an assertion failure. It expected 5 but it received 4
> 
> This issue is unrelated to this PR, as it's already in main. When running gradle clean build test on directory where changes were made (cart-service), everything passes, so it's not these changes that are of cause.

@cgerard321

**Review by cgerard321 — APPROVED** [review]

**Review by viktorkuts — APPROVED** [review]
Looks good, qodana was also fixed to pass.
Good for merge

**Review by Hares-2088 — APPROVED** [review]
Test and all good

**Pull request merged**
