### PR TITLE
bug/CART-CPC-1268 Restore VSCode Folder

### PR DESCRIPTION
**Pull request by Drexjar**
JIRA: 
[link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1268)

## Context:
This PR restores the .vscode folder in petclinic-frontend that was accidentally deleted in a previous commit. The folder is crucial for ensuring consistent development settings and should not be removed. Silly me.

## Does this PR change the .vscode folder in petclinic-frontend?:
Yes, it restores the .vscode folder that was accidentally deleted.

## Changes
Restored the .vscode folder in petclinic-frontend to its previous state.

## Dev notes (Optional)
Won't happen again.

### CODE REVIEW

**Comment by cgerard321** [comment]
What is the jira ticket for this?

**Comment by Drexjar** [comment]
> What is the jira ticket for this?

The PR is updated with the jira ticket.

**Review by cgerard321 — APPROVED** [review]
It looks okay. Hopefully, people who don't have the extensions already get the alert from the IDE. 

Branch name doesn't follow the naming convention though. It's probably too late to fix it now.

**Review by nic5694 — APPROVED** [review]
I updated your branch myself to add the files back since over the past couple of days the .vscode folder has been missing. Glad you realized that you saw the mistake and opened the pr. The CI check that failed was not your fault it was just a docker pull rate issue, it is common when running these CI checks on common runners like github actions. I will merge this so people have the updated config.

**Pull request merged**
