### PR TITLE
Feat/BILL-CPC-1046) Allows a User to get all their bills (db bug fix included)

### PR DESCRIPTION
**Pull request by Futurespast**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1046?atlOrigin=eyJpIjoiYmE3MTgzYzlhZWQ4NGQ4YmI4ZTRhMWYwYjgwYTg2YjgiLCJwIjoiaiJ9

## Context:
This ticket creates the main billing page for the customer and allows them to see all their bills (by customer id). This way the billing in the nav bar now redirects them to their billing page and the customer can see all their bills. **Please note, I have accidently fixed and properly configured the database in this branch. Therefore a new branch will not be created despite the separate story.**

## Changes

- creation of a new customer billing page
- a billing table to get and handle all the bills
- bill model in the front end
- modified path.routes, router and AppNavBar to have the frontend access the newly created page
- fixed the mongo db to actually have customer ids and moved it to the proper layer
- added new controller for old v2 angular frontend
- added testing for the new controller

## Before and After UI (Required for UI-impacting PRs)

image

### CODE REVIEW

**Review by flyindonut — APPROVED** [review]
Good adjustments, everything looks good!

**Comment by Futurespast** [comment]
oops forgot to take a new screenshot for the image. It doesn't have the customer id in the url anymore.

image

**Review by ctsaki25 — APPROVED** [review]
Looks good👍

**Comment by cgerard321** [comment]
"added new controller for old v2 angular frontend" - I'm confused. The new V2 controller is for the react frontend (or it should be). Can you confirm that you did this correctly?

**Comment by Futurespast** [comment]
yeah, I confused the two. I meant added new controller for the react front end (v2)

**Pull request merged**
