### PR TITLE
Feat(VIST-CPC-1322) Create A Refresh Button For All The Emails

### PR DESCRIPTION
**Pull request by FelixAllard**
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1322)
## Context:
Added a refresh button to the project and made some space on the emailing page for the implementation of the mailbox
## Does this PR change the .vscode folder in petclinic-frontend?:
No Changes
## Changes
Added a refresh button to the project and made some space on the emailing page for the implementation of the mailbox.

## Before and After UI (Required for UI-impacting PRs)
BeforeUI
image
image

## Dev notes (Optional)
The emailing page might look a little empty but it is simply because I will be adding something in the near future to the right of the page!

### CODE REVIEW

**Review by CharlesS42 — APPROVED** [review]

**Review by Rrregine — APPROVED** [review]
A good improvement for UI! I can see it's a small change of the code.

**Comment by Valthefirst** [comment]
Congrats on being PR no 1000 I kinda wanted it🥲

**Comment by FelixAllard** [comment]
Thanks! It took a lot of patience to reach here and I couldn't have done it without everyone's help @Valthefirst

**Comment by ioannisp03** [comment]
PR #1000. Congrats

**Pull request merged**
