### PR TITLE
Feat(VETS-CPC-229): Error Handling

### PR DESCRIPTION
**Pull request by Louenes099**
Upgraded error handling and removed useful classes

### CODE REVIEW

**Comment by Louenes099** [comment]
image
image
image
Proof of everything working

**Review by SmoothWin — APPROVED** [review]
Checked build logs and shariful demoed the test in person with good proof of the application working

**Comment by Louenes099** [comment]
image

More proof that everything works

**Review by BunTymofiy — APPROVED** [review]
Tested on my end and it worked.

**Review by Iana-Sha — APPROVED** [review]
Way better now!

**Pull request merged**
