### PR TITLE
feat(INVT-CPC-1052): Fix Edit Inventory

### PR DESCRIPTION
**Pull request by Sunveerg**
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1052)
## Context:
This push is for the front end and back end of the edit inventory button
## Does this PR change the .vscode folder in petclinic-frontend?:
No

## Changes

- The edit button looks a little different with colors and text
- When you click the button, it redirects you to a new page
- The new page has a form pre-populated with the information on the inventory 
- You can edit the form and save

## Before and After UI (Required for UI-impacting PRs)
image
image
image

## Dev notes (Optional)
Please accept my Pull Request

### CODE REVIEW

**Review by CharlesS42 — APPROVED** [review]
Beautiful Interface, easy to work with

**Comment by viktorkuts** [comment]
Please make sure you are not changing anything breaking in product folder, since https://github.com/cgerard321/champlain_petclinic/pull/655 broke our stuff. Thanks.

**Comment by Sunveerg** [comment]
Yeah I didn't touch that don't worry

**Review by viktorkuts — APPROVED** [review]
Changes to config files and other services were made by the linting (removing whitespace etc).
Looks good

**Pull request merged**
