### PR TITLE
feat(APIG-CPC-51): Get User Request (Auth)

### PR DESCRIPTION
**Pull request by Owalf**
- Added AuthServiceClient
- Added UserDetails dto
- Added auth-service in application.yml
- Added mapping for the get user request
- Added testing for the get user request

### CODE REVIEW

**Review by LawrenceLiang02 — COMMENTED** [review]
Seems good

**Review by LawrenceLiang02 — APPROVED** [review]

**Review by VladPopa616 — APPROVED** [review]
Everything seems good here! All tests pass.

**Review by LawrenceLiang02 — APPROVED** [review]
I see you have refactored the code, and everything is correctly renamed.

**Review by VladPopa616 — DISMISSED** [review]

**Review by Kenny-star — APPROVED** [review]
Why doesnt it build?

**Review by VladPopa616 — APPROVED** [review]
Everything seems good here.

**Review by LawrenceLiang02 — APPROVED** [review]
Seems no error

**Pull request merged**
