### PR TITLE
bug(PROD-CPC-1411): average rating unexpected behavior fix

### PR DESCRIPTION
**Pull request by viktorkuts**
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1411
## Context:
Average rating seemed to be incorrectly implemented inside the DataLoader. This PR fixes this by adding Ratings in the DataLoader.
## Changes
- Added Ratings to DataLoader
- Removed hardcoded averageRatings in the Product entity
- Reverted updateProduct method to commented out one
## Dev notes (Optional)
As the updateProduct has been reverted, please verify all edit methods work on your end. I have tested them and they work, but please do the due diligence to test if it didn't break anything.

### CODE REVIEW

**Comment by viktorkuts** [comment]
Forgot about the tests depending on the hardcoded average rating, will commit a fix soon.

**Review by Valthefirst — DISMISSED** [review]
Well done switching to the Rating entity instead of useing the averageRating field and unrelated but I love this rating you left🤣
image

**Review by J91-cloud — APPROVED** [review]
Good and necessary changes were made. Good Job

**Review by ZacharyLelievre — CHANGES_REQUESTED** [review]
I noticed that the average rating for the product is being displayed with too many decimal places (3.3333333333333335 / 5). For a cleaner UI, maybe rounding the rating to two decimal places, but other than that everything works with the new implemention you did.
image

**Comment by ZacharyLelievre** [comment]
> I noticed that the average rating for the product is being displayed with too many decimal places (3.3333333333333335 / 5). For a cleaner UI, maybe rounding the rating to two decimal places, but other than that everything works with the new implemention you did. image

The bug has been fixed
image

**Review by ZacharyLelievre — APPROVED** [review]

**Review by ZacharyLelievre — APPROVED** [review]
The bug has been fixed
image

**Review by J91-cloud — APPROVED** [review]

**Pull request merged**
