### PR TITLE
feat(INVT-CPC-862): apig return proper on delete and post and update tests in api gateway

### PR DESCRIPTION
**Pull request by nic5694**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-862
## Context:
Changed the return status code in the API gateway of every single controller method and updated incorrect and faulty tests.
## Changes
Fixed the expected status codes from the tests and rewrote faulty integration tests. Optimized tests and optimized a request for the visits service due to it being tied to one of the faulty tests that were failing. 
## Before and After UI (Required for UI-impacting PRs)
N/A
## Dev notes (Optional)
- Used a URI builder to make the domain client request to build a safe URI
## Linked pull requests (Optional)
N/A

### CODE REVIEW

**Comment by swafit** [comment]
Have you verified that the UI has not changed by adding text_event_stream_value to the flux(not sending all the data) ?

**Review by Nmazza1 — APPROVED** [review]
Not much to say other than proper response codes help with debugging 👍

**Comment by nic5694** [comment]
> Have you verified that the UI has not changed by adding text_event_stream_value to the flux(not sending all the data) ?

Yeah, i commented out the event stream for the links that have not implemented reactive requests.

**Review by SandwichKing978 — APPROVED** [review]
Looks good and good job on fixing the return types and adding response entity in places that are needed.

**Review by AlexeiTimbro — APPROVED** [review]
Everything looks good great job Nicholas keep it up.

**Review by SandwichKing978 — DISMISSED** [review]
Looks good, good job on adding the proper returns for post and put

**Review by SandwichKing978 — APPROVED** [review]
looks good, good job on adding the proper returns.

**Review by RichardDanon — APPROVED** [review]
Everything looks fine this code looks ready to be merged from my point of view.

**Review by AlexeiTimbro — APPROVED** [review]
The code looks code good, keep it up Nicholas.

**Pull request merged**
