### PR TITLE
feat(BILL-CPC-1203): Make pages for bills (Admin)

### PR DESCRIPTION
**Pull request by ctsaki25**
**JIRA:** 
https://champlainsaintlambert.atlassian.net/browse/CPC-1203?atlOrigin=eyJpIjoiNWNmOTE0ODQ3MzA1NDM5MWIzOGRhYWM0ODZiNmE2M2UiLCJwIjoiaiJ9
## Context:
This feature splits all the bills in the admin page into separate pages (10 bills per page) to make the page less long.
## Does this PR change the .vscode folder in petclinic-frontend?:
No

<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes

- Admin bills list is split into 10 bills per page
- Created new getAllBillsPaginated method and endpoint
- Added page navigation buttons at the bottom of the page
- Added Bill Service Implementation tests
- Added Bill Resource Integration tests
- Added Bill Resource Unit tests
- Added Bill Service Client Integration tests
- Added Bill Controller Integration tests
- Added Bill Controller Unit tests

## Before and After UI (Required for UI-impacting PRs)

Before:
sf

After:
Screenshot 2024-10-05 at 10 22 58 PM

### CODE REVIEW

**Comment by ctsaki25** [comment]
goodnight thx

**Review by ctsaki25 — COMMENTED** [review]
wow this looks really good constantine good job

**Review by Futurespast — APPROVED** [review]
This is incredibly impressive work and I'm glad you were doing this feat and not me haha.

**Review by PaoloOabel — APPROVED** [review]
This is a great feature that really improves the look of the page. Previously, the long list of items made it hard to look out, limiting ten bills per page will greatly improve readability. The only thing is you also implemented the delete feature, ideally we should only implement one feature per branch.

**Pull request merged**
