### PR TITLE
Fixed different filter searches, and removed inventoryId from the visual

### PR DESCRIPTION
**Pull request by igouriny**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1045 
## Context:
Fixed the front-end of supply inventories to be more user friendly. Also fixed filter searches, where they wouldn't be working when either combined, or would only work when pressing the "search" button, which also isn't user-friendly
## Changes
- Removed the inventoryId from the visual front-end
- Changed products inside of the inventories to be referred to as supplies
- Added more inventories, inventoryTypes, and supplies to the database
## Before and After UI (Required for UI-impacting PRs)
Before: 
image

After:
Screenshot 2024-09-17 at 2 20 50 PM

## Dev notes (Optional)
- Removed commented out data (used by previous years)

## Linked pull requests (Optional)
- https://github.com/cgerard321/champlain_petclinic/pull/631

### CODE REVIEW

**Review by vinivelozo — APPROVED** [review]
Certified.

**Review by Th0masL3 — COMMENTED** [review]
Nice fix, works better.

**Review by Th0masL3 — APPROVED** [review]
Nice fix, works better now.

**Comment by CharlesS42** [comment]
Certified.

**Pull request merged**
