### PR TITLE
feat/(PROD-CPC-1184): Edit Product in Details

### PR DESCRIPTION
**Pull request by ThomasBedard**
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1184?atlOrigin=eyJpIjoiYWU3MWJjMTIxZDMyNDk0OGFhZjI1ZjliZmQ4ZDQ2OGEiLCJwIjoiaiJ9
## Context:
This user story is to allow Admins to edit products in the product details page.

## Changes
Added:
- EditProduct tsx and css file
- necessary routes to routes.tsx and path.routes.ts
- button in product details page to redirect to the edit form for each product.
- Tests in the api gateway for the update product error handling
## Before and After UI (Required for UI-impacting PRs)
Before:
Screenshot 2024-10-04 at 2 42 34 PM
After:
Screenshot 2024-10-04 at 2 46 02 PM
Screenshot 2024-10-04 at 3 07 20 PM
Screenshot 2024-10-04 at 3 07 28 PM
Screenshot 2024-10-04 at 3 08 22 PM
Screenshot 2024-10-04 at 3 08 34 PM

## Dev notes
The css is in another fix PR. I am also aware that when the product name is changed the description is removed because of the way product descriptions were implemented. Another issue I am aware of is the fact that you have to reload the product to see the updated version is recently viewed products.

### CODE REVIEW

**Review by ZacharyLelievre — DISMISSED** [review]
Tested the branch, and everything works well. The issue with added products not displaying on the product detail page is due to a previous hard-coded implementation, which is unrelated to this PR. Approving this, as the fix will be handled in the next sprint.

**Review by ZacharyLelievre — APPROVED** [review]
Tested and confirmed that the issue regarding the inventory manager not being able to edit the product has been successfully fixed. Everything works as expected, and as an inventory manager, I can now edit the product. Great job!

**Review by Elvis-elvis — DISMISSED** [review]
The edit feature works well the only thing that's not properly working (not related to this sprint) is when you edit the name it will not give the description as it is hard coded but as discussed that's an issue to be fixed

**Review by Elvis-elvis — APPROVED** [review]
The edit feature works well the only thing that's not properly working (not related to this sprint) is when you edit the name it will not give the description as it is hard coded but as discussed that's an issue to be fixed

**Review by ZacharyLelievre — APPROVED** [review]
Tested and confirmed that the issue regarding the inventory manager not being able to edit the product has been successfully fixed. Everything works as expected, and as an inventory manager, I can now edit the product. Great job!

**Pull request merged**
