### PR TITLE
Bug/cstm cpc 793 fix reactive owner controller get owner by owner Id

### PR DESCRIPTION
**Pull request by Youssefchahboune**
JIRA: https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/14?modal=detail&selectedIssue=CPC-793&sprint=302
## Context:
the ticket is about fixing the getOwnerByOwnerId and at the same time creating a public Id / UUID for the owner
## Changes
- Changed database ownerId to a public ID/UUID called 'ownerId.'
- Enhanced the 'getOwnerByOwnerId' endpoint to return proper DTOs and adhere to conventions.
- Updated the API gateway to use the Reactive Customer Service.
- Added tests to verify the functionality of 'getOwnerByOwnerId.'
- These changes will impact all microservices that use 'ownerId' as an integer or 'owner.getId()' to retrieve a specific owner.

## Before and After UI (Required for UI-impacting PRs)

After :
image

Before : 

image

After: 

image

## Dev notes (Optional)
- Specific technical changes that should be noted
## Linked pull requests (Optional)
- pull request link

### CODE REVIEW

**Review by Nmazza1 — APPROVED** [review]
Obviously due to the change with the ID the tests need to be re-written not only for customers but I'd imagine any other service that may try to refer back to the ID, such as bills. Other than that it looks good!

**Comment by Saimirz** [comment]
Everything seems to be pretty good. This change is going to affect many of the other services, but it is defenitely a needed change.

**Review by Saimirz — DISMISSED** [review]
The code looks pretty good. The changes made will affect the other services, but it is definitely a needed change.

**Review by Saimirz — APPROVED** [review]
The code looks good. These changes will affect a lot but we need them.

**Review by Nmazza1 — APPROVED** [review]
Besides the obviously previously mentioned need for updated tests, this appears to be fine. Though I don't understand the need for a second push before merging.

**Pull request merged**
