### PR TITLE
feat(AUTH-CPC-104): password reset

### PR DESCRIPTION
**Pull request by zellyk**

### CODE REVIEW

**Comment by Trilikin21** [comment]
rename pr to follow naming convention

**Review by Trilikin21 — DISMISSED** [review]
Because of the lack of time left in this sprint, I will accept this PR, but some of the test implemented are not good for the controller. You will need to fix it in the next sprint.

**Review by JordanAlbayrak — DISMISSED** [review]
As Jeremy said, it will be put into main due to the deadline of sprint 1, but bugs can be fixed during the next sprint.

**Review by MaxGrabs — APPROVED** [review]

**Review by ArianneBonneau — APPROVED** [review]
to be continued in sprint 2.. (tests are not complete)

**Pull request merged**
