### PR TITLE
feat(APIG-CPC-62) Delete User Request (Auth)

### PR DESCRIPTION
**Pull request by Owalf**
- Added mapping for the delete user request
- Added testing for the delete user request

### CODE REVIEW

**Review by Kenny-star — DISMISSED** [review]
LGTM!

**Review by VladPopa616 — DISMISSED** [review]
This seems good! One thing, you have a merge conflict, just solve that please.

**Review by LawrenceLiang02 — DISMISSED** [review]
Seems good to me

**Review by LawrenceLiang02 — APPROVED** [review]
Seems to me that you renamed some stuff

**Review by Ludo67 — APPROVED** [review]

**Pull request merged**
