### PR TITLE
Feat/prod cpc 1121 apply trending products section

### PR DESCRIPTION
**Pull request by J91-cloud**
**JIRA:** link :

https://champlainsaintlambert.atlassian.net/browse/CPC-1121

## Context:
In this feature i applied the top 4 trending products we have. I had to add a new variable in Product entity. This variable should reset after 30 days. 

## Does this PR change the .vscode folder in petclinic-frontend?: This feature did not change the .vscode folder. 

Be sure to include cgerard321 as a reviewer.

<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes

Added a variable inside the responseModels, and product entity.

Added positive/negative tests for my requestCount methods. 

Added a UI component returning trending products. 

Added my patch request inside the api-gateway and serviceImpl in products.

Created a getProductByProductId in the front-end, so when a user does this action it can patch the product. 

## Before and After UI (Required for UI-impacting PRs)
PR SC Trending

### CODE REVIEW

**Comment by J91-cloud** [comment]
I am reviewing why the cart service failed. It is because of the new reqeustCount field added to the response model .

**Review by ZacharyLelievre — DISMISSED** [review]
The trending products feature was tested successfully and functions as expected, allowing me to view the trending products at the top.

image

**Review by ThomasBedard — DISMISSED** [review]
Fixes have been implemented 👍

**Review by viktorkuts — APPROVED** [review]
Looks good

**Review by ZacharyLelievre — APPROVED** [review]
Changes were tested on my end. Approving merge.

**Pull request merged**
