### PR TITLE
Feat/cstm/cpc 791/worked on end points

### PR DESCRIPTION
**Pull request by Nmazza1**
JIRA:
https://champlainsaintlambert.atlassian.net/browse/CPC-791?atlOrigin=eyJpIjoiNDgwMTNjOTdkN2ZmNDQ3Njk1ZWFjOWM2MGY4M2RhZWMiLCJwIjoiaiJ9
## Context:
The old pet response was a PetDTO returning the private ID
## Changes
Made PetResponseDTO
Return public ID
Added Pet Details Page with some buttons
## Before and After UI (Required for UI-impacting PRs)
Before
After
## Dev notes (Optional)
-Occasional bug that OwnerResponseDTO Responds with 0 Pets in the array [Cannot repeatedly incur the bug, will make a story]
-Selling your soul to Belzebub the Eater of Worlds, End of Times Calamity helps you push Pets Data Through owners
-Probably need to consolidate Owners and Pets into one Response / Files as it is terrible discerning both

### CODE REVIEW

**Review by DisgruntledMensch — APPROVED** [review]
looks good

**Review by mattjulienn — APPROVED** [review]
petId is now a String, all tests worked and it built. Good stuff man, hard work pays off... Onto bigger things now... Keep your head up, keep your bread up... 👍

**Comment by Nmazza1** [comment]
These tests were working before what the

**Review by mattjulienn — APPROVED** [review]
Commented out tests are to be fixed next sprint, but we're still @ >90% testing right now, so that's fine. Other than that, good work, family. 👍

**Review by DisgruntledMensch — APPROVED** [review]
looks good

**Pull request merged**
