### PR TITLE
feat(VETS-CPC-1296): delete specialties by vet id and specialty id

### PR DESCRIPTION
**Pull request by Apoleh**
**JIRA:** link to jira ticket
## Context:
Admin and vets are now able to delete the vets specialties.
## Does this PR change the .vscode folder in petclinic-frontend?:
No

<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes

- implemented delete specialties in api gateway and vet service
- tested delete specialties in api gateway and vet service
- implemented the frontend for delete specialties with a button

## Before and After UI (Required for UI-impacting PRs)
Before:
image
After:
image

### CODE REVIEW

**Review by bluement — APPROVED** [review]
good amount of files changed, nothing that breaks the code and all features are there, good job

**Review by orell2j — APPROVED** [review]
You didn't affect any other services and you did it very quick, looks like the delete works according to the backend and the frontend codes. Good job

**Comment by Valthefirst** [comment]
Just curious but why is there a random file added that's empty?
File name: [26001f182148bc0120a39c3ed4a79fb]443

**Comment by Apoleh** [comment]
> Just curious but why is there a random file added that's empty? File name: [26001f182148bc0120a39c3ed4a79fb]443

I’m not sure why that file was added. I didn’t manually add it.

**Pull request merged**
