### PR TITLE
bug(BILL-CPC-926): Fix Naming

### PR DESCRIPTION
**Pull request by ctsaki25**
**JIRA:** 
https://champlainsaintlambert.atlassian.net/browse/CPC-926?atlOrigin=eyJpIjoiMDNiM2FkZWY1YTYzNDRiZjg0MTU5YzAxYjI3MDc4OGUiLCJwIjoiaiJ9
## Context:
Changed the names of many methods in the backend to fit naming conventions.

## Does this PR change the .vscode folder in petclinic-frontend?:
No.

<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes

Many improperly named methods in the backend were changed to fit the naming conventions:
- getBilling -> getBillById
- getAllBilling -> getAllBills
- getAllPaidBilling -> getAllPaidBils
- getAllUnpaidBilling -> getAllUnpaidBills
- getAllOverdueBilling -> getAllOverdueBills
- getBillingInfo -> getBillById
- getAllBillingByPage -> getAllBillsByPage
- GetAllBillsByStatus -> getAllBillsByStatus
- GetAllBills -> getAllBills
- CreateBill -> createBill
- DeleteBill -> deleteBill
- GetBillsByCustomerId -> getBillsByCustomerId
- GetBillsByVetId -> getBillsByVetId
- DeleteBillsByVetId -> deleteBillsByVetId
- DeleteBillsByCustomerId -> deleteBillsByCustomerId
- DeleteAllBills -> deleteAllBills

Changed BillResource to BillController
Also renamed SERVICE to billService in BillController

## Before and After UI (Required for UI-impacting PRs)
If this is a change to the UI, include before and after screenshots to show the differences.
If this is a new UI feature, include screenshots to show reviewers what it looks like. 
## Dev notes (Optional)
Specific technical changes that should be noted
## Linked pull requests (Optional)
Pull request links

### CODE REVIEW

**Review by PaoloOabel — APPROVED** [review]
It is good we changed these naming conventions as it became quite confusing at times.

**Review by axolot4 — APPROVED** [review]
Good naming

**Comment by ctsaki25** [comment]
oh I screwed up didn't i

**Review by axolot4 — APPROVED** [review]

**Review by Futurespast — DISMISSED** [review]
Thank you. This will make things less confusing.

**Review by MercuryAtom31 — DISMISSED** [review]
Great work. I read your story was also about fixing grammar mistakes. You could use this extension, it does a good job.
Screenshot 2024-10-18 at 21 19 03

**Review by Futurespast — APPROVED** [review]
Sorry, it was our pr's that cause merge conflicts. It was either you were going to get it or us. Maybe it would have been better if you did this first at the start and then everyone used the changes.

**Review by axolot4 — APPROVED** [review]

**Pull request merged**
