### PR TITLE
feat(MAIL-CPC-283): Add SMTP

### PR DESCRIPTION
**Pull request by Fube**
- Added SMTP
- Setup GMail SMTP
- Added MailerService

### CODE REVIEW

**Review by CrxJr — APPROVED** [review]
Files seem to work how they're supposed.  Code looks good

**Review by Louenes099 — APPROVED** [review]
Everything seems logical and not missing any components that would break main

**Comment by Fube** [comment]
What the hell happened in between the 7 hours I left?
Why did @Louenes099 review this?
Why did @Louenes099 merge main into this?

**Comment by Louenes099** [comment]
Sorry 😐😅

**Comment by Fube** [comment]
I just re-ran the jobs and now it works????
What the hell happened here?

**Review by Louenes099 — APPROVED** [review]
Won't do anything else anymore

**Pull request merged**
