### PR TITLE
Feat/auth cpc 102 signup user

### PR DESCRIPTION
**Pull request by JordanAlbayrak**
All tests passed, register/signup UI is implemented, the logic behind it is mostly done but still in the works. My sprint consisted of creating the Register UI and logic, but I only managed to completed the UI.

### CODE REVIEW

**Review by ArianneBonneau — DISMISSED** [review]
looks good!

**Comment by Fube** [comment]
Is this branched off of one of my branches?

**Review by MaxGrabs — DISMISSED** [review]
It has been reviewed and good. This won't break main.

**Comment by JordanAlbayrak** [comment]
> Is this branched off of one of my branches?

Yes, I  think I did it with you? I believe I had to do it in order to get the User classes instead of recreating them and creating possible merge conflicts.

**Comment by Fube** [comment]
> > Is this branched off of one of my branches?
> 
> Yes, I think I did it with you? I believe I had to do it in order to get the User classes instead of recreating them and creating possible merge conflicts.

Ah yes I remember that

**Pull request closed without merging**
