### PR TITLE
feat/CSTM-CPC-851 Adding Tests For Coverage

### PR DESCRIPTION
**Pull request by Saimirz**
https://champlainsaintlambert.atlassian.net/browse/CPC-851?atlOrigin=eyJpIjoiYmQxMzU2NjdjYWJkNGVlNGIxNTkyMWFhYmY5MjZmOTEiLCJwIjoiaiJ9
## Context:
Adding integration tests for coverage
## Changes
- adding tests controllerIntegrationTests
## Before and After UI (Required for UI-impacting PRs)
If this is a change to the UI, include before and after screenshots to show the differences.
If this is a new UI feature, include screenshots to show reviewers what it looks like. 
## Dev notes (Optional)
- Specific technical changes that should be noted
## Linked pull requests (Optional)
- pull request link

### CODE REVIEW

**Review by Nmazza1 — APPROVED** [review]
Good Catch on not having tests! 👍

**Review by Nmazza1 — CHANGES_REQUESTED** [review]
Put this on hold until the tests show

**Review by Nmazza1 — APPROVED** [review]
NOW we can see the tests!

**Review by Nmazza1 — APPROVED** [review]
Approval #1721346713

**Review by Youssefchahboune — APPROVED** [review]
thanks for adding the test so that we can have a better code coverage !

**Pull request merged**
