### PR TITLE
feat/(PROD-CPC-1179): Sort Products and Filtering Products by Customer Ratings

### PR DESCRIPTION
**Pull request by ZacharyLelievre**
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1179)
## Context:
This ticket is about implementing a feature that allows pet owners to sort and filter products by customer ratings on the product page. We are making this change to enhance the user experience by making it easier for users to find products , either by sorting ratings from highest to lowest or setting a custom rating range.
## Does this PR change the .vscode folder in petclinic-frontend?:
No, this PR does not change the .vscode folder.

<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes

- Added sorting functionality for customer ratings (highest to lowest and vice versa) on the product page.
- Implemented filtering options to allow users to specify a minimum and maximum rating range.
- Updated the UI to reflect the new sorting and filtering options on the product page.
- Modified the backend to support fetching filtered and sorted product data based on ratings.

## Before and After UI (Required for UI-impacting PRs)
Before:
image

After:
image

## Dev notes (Optional)
Specific technical changes that should be noted
## Linked pull requests (Optional)
Pull request links

### CODE REVIEW

**Review by J91-cloud — DISMISSED** [review]
Great Addition Zachary. I was thinking maybe you can add it so if the user requests for a minimum 2 stars but does not submit the maximum that it should still show the products. 

This image shows that at minimum 2 stars ther is no products found. 
image


>[!Note]
If you dont want users to only submit one of the 2 (min/max) maybe show an error message.

**Review by Valthefirst — CHANGES_REQUESTED** [review]
I can't see all of the components from the filter menu, I needed to zoom out to see it
image
But the main problem is that the images are gone when I filter by type
image

**Comment by ZacharyLelievre** [comment]
> I can't see all of the components from the filter menu, I needed to zoom out to see it image But the main problem is that the images are gone when I filter by type image

Thanks for pointing that out! I've fixed the issue, and the CSS has been updated with a more compact version to resolve the display problem.

**Review by J91-cloud — APPROVED** [review]

**Review by Valthefirst — APPROVED** [review]

**Comment by Valthefirst** [comment]
Just for the future maybe implement an error handling for this
image

**Pull request merged**
