### PR TITLE
conf(BILL-CPC-44) :  added packages and classes to the billing service

### PR DESCRIPTION
**Pull request by Dratorz**

### CODE REVIEW

**Comment by Fube** [comment]
Can you please remove `bash.exe.stackdump`

**Comment by Fube** [comment]
It seems your context cannot load because it is trying to connect to a datasource that does not exist
did you setup your H2 config properly?

**Comment by Dratorz** [comment]
I think that it's because there was stuff about h2 missing in my build.gradle. I just changed it but now I am not able to push my change
pushfailed
s.

**Comment by Fube** [comment]
You are unable to push because you delete that file earlier on the website and not from your local repo
Go ahead and pull down the remote and it should fix your issue

**Review by partenersintime — APPROVED** [review]

**Review by Trim0500 — CHANGES_REQUESTED** [review]
You marked as a sub task to make a presentation layer, I'm I not seeing it or has it not been added in yet? Also I saw you defined a model class, I think it would be good to write simple tests for it.[
image_2021-09-18_182232

**Review by Trim0500 — APPROVED** [review]

**Review by partenersintime — APPROVED** [review]

**Pull request merged**
