### PR TITLE
conf(INVT-CPC-708):cross_platform_conversion_for_development

### PR DESCRIPTION
**Pull request by nic5694**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-708
## Context:
What is the ticket about and why are we doing this change.
## Changes
- modified Docker file's to java version 8 or 17 depending on what was there before. Removed the "-alpine" version and commented out the commands because the commands were invalid for the version. 
- Modified docker-compose to add the platform to emulate amd64 for everyone.
## Before and After UI (Required for UI-impacting PRs)
No changes to the UI
## Dev notes (Optional)
- mySql1 - mySql3 - mySql4 now emulate amd64

### CODE REVIEW

**Review by cgerard321 — APPROVED** [review]
I verified that I could build and run the project in docker and bring it up on the browser while using a Windows computer. Everything worked as expected.

**Comment by cgerard321** [comment]
please update the PR name as it doesn't meet the naming convention.

**Comment by swafit** [comment]
Please add a jira ticket link

**Review by swafit — APPROVED** [review]
Make sure you link a ticket for this issue.

**Pull request merged**
