### PR TITLE
Feat(VISE-CPC-100): Created calendar UI 

### PR DESCRIPTION
**Pull request by Funnyadd**
Created a calender UI for the user to be able to select a date and time for their visit at the Pet Clinic. Only the front-end was done and no back-end (will be done in next sprint).

### CODE REVIEW

**Review by cjayneb — COMMENTED** [review]
I dont get why the calendarScript is both in the html and in a separate file

**Review by ArianneBonneau — COMMENTED** [review]
same as @cjayneb, else it looks good

**Review by ArianneBonneau — APPROVED** [review]
lgtm

**Review by cjayneb — APPROVED** [review]
LGTM

**Pull request merged**
