### PR TITLE
bug/(VIST-CPC-1267): Missing/Incorrect Docker Compose And CI Configuration For Emailing Service 

### PR DESCRIPTION
**Pull request by FelixAllard**
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1267)
## Context:
Just adding integration for max and Linux
## Does this PR change the .vscode folder in petclinic-frontend?:
No
## Changes
Added New GitHub CI testing
Made it mac compatible
## Before and After UI (Required for UI-impacting PRs)
No UI
## Dev notes (Optional)
- A macOS user should do a review on this pull request because it is to test if it works on macOS

### CODE REVIEW

**Comment by FelixAllard** [comment]
Do lookout for the CI test ASP.NET

**Comment by FelixAllard** [comment]
@viktorkuts Thank you for the heads-up! I'll make sure to change the ports and assert connectivity

**Comment by VladLoghin** [comment]
try using assert.AreEqual instead of assert.That, since it is giving you a warning. AreEqual might be more up to date the That in c#, this may lead less conflicts in the future as the application evolves

**Comment by FelixAllard** [comment]
I basically just changed a LOT of logic to make sure we have as less warning as possible. I also changed the git CI for better learning.

**Review by Zako563 — APPROVED** [review]
I saw that you changed the port for your emailing sql, it should work right now

**Review by ioannisp03 — APPROVED** [review]
Perfect. I see you changes the port number.

**Pull request merged**
