### PR TITLE
feat/ACMS-CPC-548 - logout button + functionality added

### PR DESCRIPTION
**Pull request by felixlabrie**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-548?atlOrigin=eyJpIjoiMzNkYzM2YWZkNjI3NDAyOWJhYTUxYzBlNGI1Y2NjMmMiLCJwIjoiaiJ9
## Context:
Add a logout button to the nav bar when a user is logged in that will logout the user from his session
## Changes
-added function that purges the token, username, and email from the client
-added the button in the nav-bar with an onClick listener 
## Before and After UI (Required for UI-impacting PRs)
See screenshots
before
after
## Dev notes (Optional)
- Specific technical changes that should be noted
## Linked pull requests (Optional)
- pull request link

### CODE REVIEW

**Review by DmitryGrigoryev21 — DISMISSED** [review]
Looks great. Tested and works as intended.

**Review by StaceyJin — APPROVED** [review]
Code reviewed and appears sound, built and tested project, functioned as expected.

**Review by DmitryGrigoryev21 — DISMISSED** [review]
Tests are now in order. Everything works as intended

**Review by StaceyJin — DISMISSED** [review]
Previously approved, code was reviewed, everything appeared in order, tests all pass now.

**Review by StaceyJin — APPROVED** [review]
Code appears in order, no change since last reviewed and approved.

**Review by AmirHamzahMirza — APPROVED** [review]
Everything looks good, everything runs as expected and performs well as well.

**Pull request merged**
