### PR TITLE
Conf/bill cpc configuring service

### PR DESCRIPTION
**Pull request by LemireCoding**
Configured and added database structure for Billing service

### CODE REVIEW

**Review by Fube — CHANGES_REQUESTED** [review]
You are missing tests
I cannot approve this
Also, in your test profile, you've disabled ddl-auto, why?

**Comment by Fube** [comment]
Correct me if I am mistaken, but your PR naming convention seems a bit off

**Comment by LemireCoding** [comment]
> Correct me if I am mistaken, but your PR naming convention seems a bit off

Did not have Jira for the issue #

**Comment by Fube** [comment]
> > Correct me if I am mistaken, but your PR naming convention seems a bit off
> 
> Did not have Jira for the issue #

Ah ok that's above my paygrade, gotta ask @cgerard321

**Pull request closed without merging**
