### PR TITLE
Feat/cstm cpc 1013 add pet weight

### PR DESCRIPTION
**Pull request by 1-emil**
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1013?atlOrigin=eyJpIjoiYjNhOTkwYmQzOTcyNDE4N2I4MmZlMzQzNzMwMjU1YTciLCJwIjoiaiJ9)
## Context:
Adding pet weight to front-end and back-end so the customer can edit the see their pet's weight and edit it
## Changes
- Add weight string
- Add weight to confirmation when submitting edit pet form
- add weight input text box to edit and add pet form
- add weight text box to pet details to see weight
## Before and After UI (Required for UI-impacting PRs)
Screenshot 2023-10-22 at 1 51 44 AM

I don't have a before image but its basically the form and confirmation message without the weight.
## Dev notes (Optional)
- I also fixed a small bug where isActive would be blank in the pet details after editing a pet.

### CODE REVIEW

**Review by DisgruntledMensch — APPROVED** [review]
Looks good, make sure all the testing is still working since you've added a new var.

**Review by Nmazza1 — COMMENTED** [review]
Why are you adding a lot of code back to Owner Details after it was moved?

**Comment by 1-emil** [comment]
> Why are you adding a lot of code back to Owner Details after it was moved?

I did not add this code I think it added when i merged main with my branch

**Review by Nmazza1 — APPROVED** [review]
In that case I suggest deleting the code if possible to keep the files organized, otherwise all good 👍

**Pull request merged**
