### PR TITLE
Feat/vist cpc 1282 add a way to filter visits by visit description

### PR DESCRIPTION
**Pull request by VladLoghin**
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1282?atlOrigin=eyJpIjoiMTkzMTE0NDU5MzAzNDE2YjgxY2QwMzk2M2RiYTAyNzEiLCJwIjoiaiJ9 
## Context:
allows for a better way to find a desired visit by searching up its description
## Does this PR change the .vscode folder in petclinic-frontend?:
If the PR changes the .vscode folder, explain why in detail because it should not. 
Be sure to include cgerard321 as a reviewer.

<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes
I have changed the getAll request to accept a parameter of type String description and have added a way to filter through visits with a search bar
This can be bullet point or sentence format.
## Before and After UI (Required for UI-impacting PRs)
Screenshot 2024-09-26 153806
Screenshot (28)

## Dev notes (Optional)
Specific technical changes that should be noted
## Linked pull requests (Optional)
Pull request links

### CODE REVIEW

**Review by Zako563 — APPROVED** [review]
I noticed that your front end does not use the back end. Maybe you can try to implement this. Overall its good and all the features are present

**Review by AlejandroBrnab — APPROVED** [review]
Try to remove comments once the pull request is done. I noticed one in the front-end part. Other than that, good job. It looks good to me.

**Comment by ioannisp03** [comment]
Hey! Naming convention for PR must be followed. Switch is to this: feat(VIST-CPC-1282): add a way to filter visits by visit description #879

**Comment by AlejandroBrnab** [comment]
> Hey! Naming convention for PR must be followed. Switch it to this: feat(VIST-CPC-1282): add a way to filter visits by visit description #879

Thank you for noticing that, I missed it before.

**Pull request merged**
