### PR TITLE
Feat/bill cpc 108 new repo module

### PR DESCRIPTION
**Pull request by LemireCoding**

### CODE REVIEW

**Comment by LemireCoding** [comment]
Need Review approval to merge New billing service into main

**Comment by Trim0500** [comment]
Seeking to put into main for other stories to be made and completed for the billing service. Only has contextloads for testing, only made a new service, no additional configuration.

**Review by Dratorz — APPROVED** [review]
Everything looks good to me

**Review by jumpung — APPROVED** [review]
Everything looks good

**Pull request merged**
