### PR TITLE
bug(VETS-CPC-1248): Fix delete vet by vet ID

### PR DESCRIPTION
**Pull request by orell2j**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1248?atlOrigin=eyJpIjoiYmRmMDM1NmMyNjE4NGY1ZmE0OGJlMDQxZWQ5NzA2OWYiLCJwIjoiaiJ9

## Context:
What is the ticket about and why are we doing this change.

This ticket is about deleting a veterinarian by their ID, the admin needs to have this ability to ensure that the list of vets is up-to-date, especially when a vet can quit or be fired. 

So this change fixes a problem where the vet was not properly deleted from the database. Also, it fixes a bug where after clicking the "delete" button, it was navigating the admin to the vet's detail page instead of staying on the list.

## Does this PR change the .vscode folder in petclinic-frontend?:

No, this PR does not modify the .vscode folder

## Changes

- Fixed the delete functionality so that it properly deletes the veterinarian record from database (MongoDB).

- Addressed a bug where, after deleting a vet, the UI would navigate to the vet's detail page. Now, the page stays on the veterinarian list and removes the deleted vet from the UI.

## Before and After UI (Required for UI-impacting PRs)

BEFORE:

1- Initial UI with "John Doe":

image

2- Attempting to Delete "John Doe": 

image

3- Reloading the page still shows the deleted vet: 

image

AFTER:

1- Initial UI with "John Doe": 

image

2- Deleted "John Doe" from the UI:

image

3- MongoDB reflecting the deletion:

image

## Dev notes (Optional)
- this fix ensures the deletion in the backend and after deletion the vet list is updated in real-time without refreshing the page

### CODE REVIEW

**Review by bluement — APPROVED** [review]
<nitpick> maybe add more comments like we discussed last time, but all is well, good job, update the branch and send it

**Comment by Apoleh** [comment]
The repository should not have 44 commits—this seems excessive. Please reduce or consolidate them. Also, the title name is incorrectly formatted; please fix it.

**Comment by orell2j** [comment]
> maybe add more comments like we discussed last time, but all is well, good job, update the branch and send it

Should I add more comments on the code and my commits?

**Comment by orell2j** [comment]
> The repository should not have 44 commits—this seems excessive. Please reduce or consolidate them. Also, the title name is incorrectly formatted; please fix it.

Sorry, I saw it too after creating the Pull Request, I don't know how to reduce the number of commits, it looks like I need to delete the branch and do a new one. I wanted to ask the teacher today, but I didn't have time because of tutoring and my part-time job. I'll question the teacher in Friday morning or just text them on teams to fix it. 

And about the incorrect formatting of the title, should I name it like "Fixing the delete button for vetId in the list"?

**Comment by Apoleh** [comment]
> > The repository should not have 44 commits—this seems excessive. Please reduce or consolidate them. Also, the title name is incorrectly formatted; please fix it.
> 
> Sorry, I saw it too after creating the Pull Request, I don't know how to reduce the number of commits, it looks like I need to delete the branch and do a new one. I wanted to ask the teacher today, but I didn't have time because of tutoring and my part-time job. I'll question the teacher in Friday morning or just text them on teams to fix it.
> 
> And about the incorrect formatting of the title, should I name it like "Fixing the delete button for vetId in the list"?

It should follow this format: feat(TEAMTAG-JiraID): short description. So in your case, it should look like this: bug(VETS-CPC-1248): fix delete vet by vet ID.

**Comment by orell2j** [comment]
> > > The repository should not have 44 commits—this seems excessive. Please reduce or consolidate them. Also, the title name is incorrectly formatted; please fix it.
> > 
> > 
> > Sorry, I saw it too after creating the Pull Request, I don't know how to reduce the number of commits, it looks like I need to delete the branch and do a new one. I wanted to ask the teacher today, but I didn't have time because of tutoring and my part-time job. I'll question the teacher in Friday morning or just text them on teams to fix it.
> > And about the incorrect formatting of the title, should I name it like "Fixing the delete button for vetId in the list"?
> 
> It should follow this format: feat(TEAMTAG-JiraID): short description. So in your case, it should look like this: bug(VETS-CPC-1248): fix delete vet by vet ID.

Understood, I fixed the title format and thanks for the helpful comment, I'll check with the teacher to questions about commits tomorrow (on Friday).

**Comment by cgerard321** [comment]
> > > > The repository should not have 44 commits—this seems excessive. Please reduce or consolidate them. Also, the title name is incorrectly formatted; please fix it.
> > > 
> > > 
> > > Sorry, I saw it too after creating the Pull Request, I don't know how to reduce the number of commits, it looks like I need to delete the branch and do a new one. I wanted to ask the teacher today, but I didn't have time because of tutoring and my part-time job. I'll question the teacher in Friday morning or just text them on teams to fix it.
> > > And about the incorrect formatting of the title, should I name it like "Fixing the delete button for vetId in the list"?
> > 
> > 
> > It should follow this format: feat(TEAMTAG-JiraID): short description. So in your case, it should look like this: bug(VETS-CPC-1248): fix delete vet by vet ID.
> 
> Understood, I fixed the title format and thanks for the helpful comment, I'll check with the teacher to questions about commits tomorrow (on Friday).

The problem is that you did a merge at some point (probably by doing git pull without the --rebase or you used the IDE to do it (it usually does a merge). You now have all the commits to main that were done between when you created the branch and now on your branch. This is what you are NOT supposed to do. So you need to create a new branch off of your updated local main branch and redo your changes.

**Pull request closed without merging**
