### PR TITLE
conf(INVT-CPC-877): Closed the opened ports to the services in the docker-compose

### PR DESCRIPTION
**Pull request by nic5694**
Took 7 minutes

JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-877
## Context:
Closing the ports on the servuces
## Changes
- Closed ports in AUTH and Customer service
- Requests to the service now needs to be done within curl locally in the docker container.
This can be bullet point or sentence format.
## Before and After UI (Required for UI-impacting PRs)
- No changes to the UI
## Dev notes (Optional)
- If you don't know how to write your curl commands with the payload write the request in postman and it will generate the appropriate Curl command with the payload

### CODE REVIEW

**Review by Matthewtan9 — APPROVED** [review]
Look good.

**Comment by Nmazza1** [comment]
Not sure how I feel about this, I feel like having 8090 open helps with developmental issues.

**Comment by nic5694** [comment]
> Not sure how I feel about this, I feel like having 8090 open helps with developmental issues.

Your product owner has been aware and was supposed to inform you last Sunday about the changes. Tests can be done within docker. Like i mentioned in the Explanation above you can easily generate the commands on postman.

**Comment by Nmazza1** [comment]
> > Not sure how I feel about this, I feel like having 8090 open helps with developmental issues.
> 
> Your product owner has been aware and was supposed to inform you last Sunday about the changes. Tests can be done within docker. Like i mentioned in the Explanation above you can easily generate the commands on postman.

I aint reading allat 😆

**Pull request merged**
