### PR TITLE
bug(CSTM-CPC-865)Fixed Pet Database Initialization Bug

### PR DESCRIPTION
**Pull request by Nmazza1**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-865?atlOrigin=eyJpIjoiNmNlNDc1ZmMyMWQ3NGM5Yzk2ZmNkOWIxMjY5OGM3NDkiLCJwIjoiaiJ9
## Context:
On occasion some owners would not have pets attached to them / could not be found from the owners ID
## Changes
-Changed the way the DB Initializer works, works consistently
## Dev notes (Optional)
This works well on my end, let me know if it doesn't work for you. Why are the tests still failing though 🤔

### CODE REVIEW

**Review by DisgruntledMensch — DISMISSED** [review]
Everything looks good to me, good job brah

**Review by Youssefchahboune — DISMISSED** [review]
which test are failing ?

**Comment by Nmazza1** [comment]
> which test are failing ?

If I remember correctly almost all tests associated with Pets. It's telling me there's an issue with the data source initializer even though when the project is ran practically there is no issues.

**Review by Youssefchahboune — APPROVED** [review]
Are the test still failing ?

**Comment by Nmazza1** [comment]
> Are the test still failing ?

yes, somethings wrong with the test environment for pets, that's for my next story I have to fix. Almost all pet tests fail due to some error with the test environment not initializing something properly

**Review by DisgruntledMensch — APPROVED** [review]
Looks good to me, I hope this fixes the UI problems we're having with owner details

**Pull request merged**
