### PR TITLE
conf(VISE-CPC-125): Multi-step Dockerfile set up

### PR DESCRIPTION
**Pull request by cjayneb**

### CODE REVIEW

**Review by Fube — DISMISSED** [review]
Just make sure you are using the OpenJDK version you need
Usually 8 is good enough but in some niche cases you need to upgrade to 11
Other than that, LGTM 👍

**Comment by zellyk** [comment]
LGTM 👍

**Review by zellyk — APPROVED** [review]
LGTM

**Review by Funnyadd — APPROVED** [review]
LGTM

**Pull request merged**
