### PR TITLE
bug(VIST-1267): Missing/Incorrect docker compose and CI configuration for emailing-service (#420)

### PR DESCRIPTION
**Pull request by FelixAllard**
[**JIRA:** link to jira ticket](https://github.com/cgerard321/champlain_petclinic)
## Context:
This change is to make sure that the MySQL works for non Windows user. It is also made to create the GitHub CI integration test, and we also removed the hard-coded keys that were in the code.
## Does this PR change the .vscode folder in pet clinic-frontend?:
No

## Changes
I modified the Emailing System program.cs, and it's appsettings.json to make sure the keys to the database don't appear anywhere. Also modified the  GitHub folder to add the CI file
## Before and After UI (Required for UI-impacting PRs)
There were no UI changes
## Dev notes (Optional)
I DO NOT have a macOS or a Linux machine, as such I have no way to know if the changes I made are working properly on Non-Windows machine. This review should be approved by at least 1 mac or Linux user

### CODE REVIEW

**Comment by FelixAllard** [comment]
So the ASP.NET CI test does work which was one of the thing that was implemented.

**Comment by ZacharyLelievre** [comment]
I launched the application on Docker and it worked on my Mac.
Screenshot 2024-09-25 at 12 53 54 PM

**Comment by ZacharyLelievre** [comment]
When running HTTP request it told me it has a problem with the container
Screenshot 2024-09-25 at 1 00 55 PM

**Comment by viktorkuts** [comment]
Docker builds and runs emailing-service on Linux 6.10.10-arch1-1 however creates an exception whenever trying to access e-mail
image

**Comment by flyindonut** [comment]
> When running HTTP request it told me it has a problem with the container

The orange warnings just mean that these containers are performing poorly on your Mac because they're using amd64 images.

**Pull request closed without merging**
