### PR TITLE
bug(AUTH-CPC-102): Signup user

### PR DESCRIPTION
**Pull request by JordanAlbayrak**
Fixed issue with UserController using the UserRepo instead of the UserService, modified a related test aswell. Also changed "Agony" to "Roles" in the Roles UI page. Tested to make sure this doesn't break main.

### CODE REVIEW

**Comment by Fube** [comment]
Fix your PR name to match the convention

**Review by Fube — CHANGES_REQUESTED** [review]
Why does UserService take in a User?
Should it not be a DTO?

**Review by Trilikin21 — APPROVED** [review]
You fixed your controller, as well as your test.

**Review by Fube — APPROVED** [review]
LGTM 👌

**Review by Trilikin21 — APPROVED** [review]
Corrected the method parameters to accept a dto instead of a user. Good job

**Pull request merged**
