### PR TITLE
feat(VETS-CPC-1387): rework home page ui

### PR DESCRIPTION
**Pull request by kyrusho**
**JIRA:** [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1387)

## Context:
Users may now have a preview of three vets from our PetClinic team, who each have services they offer. They can also click on a vet they would like to know more about to see their details on the VetDetails page.

## Does this PR change the .vscode folder in petclinic-frontend?:
No, it does not.

## Changes
- Users now see a preview of three randomly selected vets from the PetClinic team.
- Each vet card shows the vet's name, services offered, and a photo.
- Clicking on a vet card navigates the user to the respective VetDetails page.
- Services offered by vets are randomly selected and displayed as bullet points.
- Home page UI has been updated in general.

## Before and After UI (Required for UI-impacting PRs)
Before:
image

After:
image

### CODE REVIEW

**Review by Sunveerg — APPROVED** [review]
The new UI looks much better now!

**Review by NtsoaElie — APPROVED** [review]
Good job on making our home page look more warm and welcoming.

**Review by ZacharyLelievre — APPROVED** [review]
Nice work! The changes improve the user experience with a clear preview of vets and their services. The random selection adds a nice touch, and the home page looks great. Approved!

**Review by NotZagreus — APPROVED** [review]
Consider caching the fetched vet photos to reduce the number of API calls, especially when the user revisits the page. Additionally, you might want to display a loading indicator while fetching the photos to enhance the user experience. Except for that, it looks good.

**Review by hristoiv11 — APPROVED** [review]
Good implementation. I like the way it displays 3 random vets each time you refresh the page, which improves the user experience.

**Review by Zako563 — APPROVED** [review]
Thank you for improving the Home page.  The new Ui is far better than the old one.

**Review by PaoloOabel — APPROVED** [review]
The new page gives more information about the pet clinic in a pleasant way. The cards displaying the vets and their specialties helps users find what they are looking for faster. Overall, great rework!

**Pull request merged**
