### PR TITLE
feat(INVT-CPC-1231): Add Back Button

### PR DESCRIPTION
**Pull request by Sunveerg**
[**JIRA:** link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1231)
## Context:
This push is to add the back button which helps to navigate back to inventories once you are in products and also some changes in the edit inventory form
## Does this PR change the .vscode folder in petclinic-frontend?:
No

## Changes

- Added back button
- UI changes for edit inventory form

## Before and After UI (Required for UI-impacting PRs)
Before
image
image
After
image
image

## Dev notes (Optional)
Please accept my Pull Request

### CODE REVIEW

**Review by vinivelozo — APPROVED** [review]
Great changes for the front end. You edit page looks great. Also, the back button was needed. Great work and you did not touch the vscode.

**Review by CharlesS42 — APPROVED** [review]
The UI is way better than it was before. I think the form looks great with a formal approach.
(Nitpick) Have you considered changing it for a darker team like the products page?

**Comment by Sunveerg** [comment]
> Great changes for the front end. You edit page looks great. Also, the back button was needed. Great work and you did not touch the vscode.

Thanks!

**Comment by Sunveerg** [comment]
> The UI is way better than it was before. I think the form looks great with a formal approach. (Nitpick) Have you considered changing it for a darker team like the products page?

I have but we still need to experiment all the theme options to find the right one

**Pull request merged**
