### PR TITLE
Bug/cstm cpc 1014 fix pet date and update pet form

### PR DESCRIPTION
**Pull request by 1-emil**
JIRA: [link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-1014?atlOrigin=eyJpIjoiZjM2MmVjMTcyNGRlNGE1Njg2YjdkOTRlODJmNjM5NGMiLCJwIjoiaiJ9)
## Context:
There's a bug with the date and edit pet form since the new pet details page has been added, this pr fixes the issues
## Changes
Fixed pet birth date on owner details page and pet details page and also removed the duplicate pet type selector on edit pet form
## Before and After UI (Required for UI-impacting PRs)
before
image
after
im7age

### CODE REVIEW

**Review by Nmazza1 — APPROVED** [review]
Weird. I didn't see two pet type selectors on my machine. Could it be  a OS or browser specific issue?

**Comment by 1-emil** [comment]
> Weird. I didn't see two pet type selectors on my machine. Could it be a OS or browser specific issue?

Yeah probably from my end or weird merging issues but hopefully this pr will fix it for me and for everyone else assuming they also had 2 selectors in edit pet form

**Comment by swafit** [comment]
> > Weird. I didn't see two pet type selectors on my machine. Could it be a OS or browser specific issue?
> 
> Yeah probably from my end or weird merging issues but hopefully this pr will fix it for me and for everyone else assuming they also had 2 selectors in edit pet form

What do you mean by hopefully this pr will fix it?

**Comment by Nmazza1** [comment]
> > > Weird. I didn't see two pet type selectors on my machine. Could it be a OS or browser specific issue?
> > 
> > 
> > Yeah probably from my end or weird merging issues but hopefully this pr will fix it for me and for everyone else assuming they also had 2 selectors in edit pet form
> 
> What do you mean by hopefully this pr will fix it?

Assuming this bug happens in certain cases this PR will fix it.

**Review by DisgruntledMensch — APPROVED** [review]
All good lad

**Pull request merged**
