### PR TITLE
feat(CSTM-CPC-829) Add Register Owner

### PR DESCRIPTION
**Pull request by mattjulienn**
JIRA: (https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/14?search=register&selectedIssue=CPC-829)
## Context:
The purpose is to Add Register Owner functionality (Testing incl.)
[FRONT-END is commented out. I've already spent 15+ hours working on front end, and after asking every peer on my team, and many many people from other teams, and still not being able to add Register page, I'm at a complete standstill until Friday's meeting. (I'm going insane)]
## Changes
On top of now being able to add an owner... OwnerID was null thus inaccessible from the owners tab of the website, now OwnerID gets created and assigned to OwnerID granted the capability to access and edit an Owner after creation.
## Before and After UI (Required for UI-impacting PRs)
image
image

### CODE REVIEW

**Comment by Nmazza1** [comment]
Update the ticket info first with the requirements listing in your comment

**Review by Nmazza1 — DISMISSED** [review]
Yeah 👍

**Review by Youssefchahboune — CHANGES_REQUESTED** [review]
Need to add test in the ApiGateway Service + separate the Register page from delete and edit + the insert should take an ownerRequestDTO not a ownerMono.

**Review by mattjulienn — COMMENTED** [review]
See Branch Description

**Review by Youssefchahboune — APPROVED** [review]
great work now the add owner works ! but in the next sprint we are going to be splitting the delete , edit and register page into 3 different pages.

**Review by Nmazza1 — APPROVED** [review]
Good stuff but make sure to update your tests after once Saif's merge gets accepted.
OwnerDTO -> OwnerRequesDTO

**Pull request merged**
