### PR TITLE
feat(VIST-CPC-845): implement domain client layer to visits service

### PR DESCRIPTION
**Pull request by TheyCallMeCris**
JIRA:[ link to jira ticket](https://champlainsaintlambert.atlassian.net/browse/CPC-845)
## Context:
Visits-Service is an aggregator and it didn't have a domainClient. In order to implement effective Exception Handling, we needed to be able to check if the petId and vetId(practitionerId) were valid.
## Changes
I have added vetClient and petClient with getId to their service. I have added Exception Handling to these Clients. Tests Have all been updated because of these changes. Jacoco coverage is currently at 94%! I have also changed PractitionnerId and petId to String type.
## Before and After UI (Required for UI-impacting PRs)
No changes to the UI

### CODE REVIEW

**Review by Mila5847 — DISMISSED** [review]
The changes look good to me :). The tests are also present and as you said, they cover 94%. I also saw the change for the PractitionnerId to String.

**Review by Youssefchahboune — CHANGES_REQUESTED** [review]
petId is not an int but a string

**Review by CptDoritos — DISMISSED** [review]
Changes have been approved

**Review by Youssefchahboune — DISMISSED** [review]
looks good ! Thanks for switching petId to a String !

**Review by Youssefchahboune — APPROVED** [review]
looks good ! Thanks for switching petId to a String !

**Review by Youssefchahboune — APPROVED** [review]
looks good ! Thanks for switching petId to a String !

**Review by CptDoritos — DISMISSED** [review]
Changes Approved

**Review by Mila5847 — DISMISSED** [review]
I see that you chnaged the petId and the practitionnerId to String from the last review I did. Looks good. Hopefully it works well with the vets-service as well since it is indirectly affected!!!

**Review by Iantomasi — APPROVED** [review]

**Review by CptDoritos — APPROVED** [review]
Once again approving this, everything still seems fine

**Pull request merged**
