### PR TITLE
feat(none): Updated README.md

### PR DESCRIPTION
**Pull request by cgerard321**
JIRA: link to jira ticketdoc
## Context:
After receiving many questions from contributors regarding the strange red and yellow errors on a git push after rebasing their branch, I deicded to highlight the passage in the README that explains what this "error" means. 

## Changes

- Highlighed the need for git push -f after a rebase and/or merge conflic resolution.
- Added a screenshot of the "error" given when you don't use the -f option.

## Before and After UI (Required for UI-impacting PRs)
If this is a change to the UI, include before and after screenshots to show the differences.
If this is a new UI feature, include screenshots to show reviewers what it looks like. 
## Dev notes (Optional)
- Specific technical changes that should be noted
## Linked pull requests (Optional)
- pull request link

### CODE REVIEW

**Review by Nmazza1 — APPROVED** [review]
Looks good, I don't see any issues that might make prod go down 👍

**Comment by mattjulienn** [comment]
Great work !! Looks good from what I can see, shouldn't cause any issues with main :)

**Comment by Saimirz** [comment]
your code made the prod go down! we want a sprint review extension!!!!!

**Comment by cgerard321** [comment]
Updated Readme

**Pull request merged**
