### PR TITLE
feat(PROD-CPC-1178): Fixed CSS Page

### PR DESCRIPTION
**Pull request by Elvis-elvis**
**JIRA:** link to jira ticket
https://champlainsaintlambert.atlassian.net/jira/software/c/projects/CPC/boards/15/backlog?selectedIssue=CPC-1292
## Context:
This ticket is for fixing the CSS in our filter as it had a bug
## Does this PR change the .vscode folder in petclinic-frontend?: No
If the PR changes the .vscode folder, explain why in detail because it should not. 
Be sure to include cgerard321 as a reviewer.

<span style="color:red">**Reviewers need to check for any changes to the 
.vscode folder and add a comment about it to their review comments.**</span>

## Changes
What are the various changes and what other modules do those changes affect.
This can be bullet point or sentence format.
- Modified the .filter-container to use flex-direction: column to display the filters vertically.
- Added a gap of 16px between filter elements for better spacing.
- Adjusted margin-bottom of filter labels to 10px for improved layout.
- Set a margin-top of 10px for both the "Apply Filter" and "Clear Filter" buttons to ensure proper spacing from the input fields.
- The filter section of the product list is affected, improving the layout of the filter options by stacking them vertically.
- No backend or other modules are affected, as these are purely style changes in the petclinic-frontend.
## Before and After UI (Required for UI-impacting PRs)
If this is a change to the UI, include before and after screenshots to show the differences.
If this is a new UI feature, include screenshots to show reviewers what it looks like. 
image
image

## Dev notes (Optional)
Specific technical changes that should be noted
## Linked pull requests (Optional)
Pull request links

### CODE REVIEW

**Review by ThomasBedard — APPROVED** [review]
CSS for filter in ProductList.css was changed and now we can see all inputs.

**Review by Valthefirst — COMMENTED** [review]
I am now able to see proprely the filter menu. There isn't much to say. There's only one file changed, only lines of code added and only one author to this PR. It all looks good except that the Jira ticket linked has nothing to do with this PR. Could you change it to the correct one?

**Comment by Elvis-elvis** [comment]
> I am now able to see proprely the filter menu. There isn't much to say. There's only one file changed, only lines of code added and only one author to this PR. It all looks good except that the Jira ticket linked has nothing to do with this PR. Could you change it to the correct one?

Yes you're right. I added the jira ticket to the wrong pr I just removed it

**Comment by Valthefirst** [comment]
And if this is a bug like I think it is don't forget to follow proper naming convention

**Review by Valthefirst — APPROVED** [review]
The jira ticket is now the correct one which is good
<nitpic
Maybe change the PR and branch name to follow conventions
nitpic>

**Pull request merged**
