### PR TITLE
Feat/(VISE CPC - 47) Implement delete capabilities for the visits

### PR DESCRIPTION
**Pull request by NickEspitalier**

### CODE REVIEW

**Review by cjayneb — COMMENTED** [review]
Everything looks fine except you shouldn't be able to setId() in the Visit class, and the last repo test for deleting an empty visit does not assert the right thing. It should assert that all the visits which were saved in the setupdb() are still there. So assert that when you findByPetId, the size of the response from the repo is still 2.

**Review by cjayneb — DISMISSED** [review]
**VisitsServiceImplTests**
whenVisitDoNotExist -> your vise object should have an id other than 1 or 2 if you actually want to test the deleteVisit method.

**PersistenceTests**
Is_Visit_Empty_Dont_Delete -> you have to assert that the repo still has two visits in it.

**VisitResourceTests**
whenValidVisitIdDeleteTheVisit -> should verify that visitService.delete(1) is called once

**Review by codingbeast666 — APPROVED** [review]
gg

**Review by bthorng — APPROVED** [review]

**Review by bthorng — APPROVED** [review]

**Review by codingbeast666 — APPROVED** [review]
lgtm

**Pull request merged**
