### PR TITLE
feat(prod cpc 1136): product view testing part 2 

### PR DESCRIPTION
**Pull request by ZacharyLelievre**
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1043
## Context:
This ticket was about implementing all the tests for the getAll request in the product service and API Gateway, and renaming the product link to 'Shop'.
## Does this PR change the .vscode folder in petclinic-frontend?:
No, this PR does not change the .vscode folder in the petclinic-frontend.

## Changes

- Added the GetAll tests for the product-service
- Added the GetAll tests for the API-Gateway
- Modified the product page link to "Shop"
## Before and After UI (Required for UI-impacting PRs)
Before:
image
After:
image

## Dev notes (Optional)
Specific technical changes that should be noted
## Linked pull requests (Optional)
[Pull request links ](https://github.com/cgerard321/champlain_petclinic/pull/639#issue-2527405557)

### CODE REVIEW

**Review by ThomasBedard — APPROVED** [review]
Did add the tests, looks good 👍

**Review by Elvis-elvis — DISMISSED** [review]
Looks good to me

**Review by ThomasBedard — APPROVED** [review]
Tests passed, looks good 👍 
tests

**Review by Valthefirst — APPROVED** [review]
All looks good nothing on the products page broke

**Pull request merged**
