### PR TITLE
feat(BILL-CPC-1234): Admin Can Create Bill

### PR DESCRIPTION
**Pull request by Futurespast**
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1234

## Context:
As an admin, I should be able to create a bill, in case of unforeseen problem, emergency  or manual entry is required. 

Acceptance Criteria:

1. Admin should have an option (a button of some kind) to start the bill creation process.
2. A form for creating the bill should be displayed.
3. Inserting incorrect information should return an error and shouldn’t create the bill
4. Putting in all the correct information, the bill should be created and the form should disappear.
5. The new bill can now be seen and is created.

## Does this PR change the .vscode folder in petclinic-frontend?:
It does not.

## Changes

- added 2 api function for a get all in vets and customers in the front-end.
- added a post function in the v2 controller.
- added testing for the post function
- modified the vets get all vets function in vets v2 controller to have it's content type be a text-event stream
- added a button and a form to the Admin bills page that lets you create a bill.

## Before and After UI (Required for UI-impacting PRs)

<h3> Before </h3>

image

<h3> After </h3>

image

image

### CODE REVIEW

**Review by ctsaki25 — APPROVED** [review]
Everything looks really good. Im surprised Vets and Owners didn't have a getAll ready in their frontend. Your tests are good but make sure you add some negative tests as well and consider changing the **title** of your PR to start with a lowercase f and removing the / to fit the naming convention. Be sure to rebase!

Perhaps you can also try separating the 'error' in the validateForm of AdminBillsListTable (i.e. "all fields are required" and "the amount must be greater than 0") in the future.

**Comment by PaoloOabel** [comment]
The UI looks really nice but we just have to add some padding to the table and form so it does not stick to the border of the page.   The dropdown menu is a really nice feature, it ensures the customer and veterinarian provided exist.

**Review by PaoloOabel — APPROVED** [review]
Other than adding more testing to cover negative outcomes, your feature is really nice. The dropdown menu and calendar are really nice touches that facilitate the user experience. The styling will be worked on in the future for sure.

**Comment by Jesse-Bourassa** [comment]
Perfect I don't see any conflicts with our code, I like the ui you implemented for you page I would recommend sending a screenshot in teams so all groups so all teams can have the same design on there page keeping the UI Consistent

**Review by Jesse-Bourassa — APPROVED** [review]

**Pull request merged**
