### PR TITLE
bug/VETS-CPC-1247_Fix_Get_Vet_By_First_Name_And_Last_Name_2

### PR DESCRIPTION
**Pull request by hristoiv11**
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/CPC-1247

## Context:
Fixed the search bar for vets. Before, you needed to select if you wanted to search by first name or last name, now you can directly search either by first name, last name or both. I also, added a "Clear" button to clear the search bar.

## Does this PR change the .vscode folder in petclinic-frontend?:
No.

## Changes
- Changed the Vet.tsx and the VetListTable.tsx.
- Removed old methods and tests in the backend and made it work only with the frontend.
- Added a clear button.

## BEFORE
image
image

## AFTER:
image
image
image

### CODE REVIEW

**Review by Edwxd — APPROVED** [review]
It was not mentioned in the PR but, I can see that the .vscode file was not touched. 
Better implementation of the get by name and last name. Cleaner front end after searching a name in the search bar.  Overall good work.

**Review by kyrusho — COMMENTED** [review]
Please put your changes in bullet forms and mention on the pull request whether the .vscode folder has been modified or not.

**Comment by Apoleh** [comment]
**fix(VETS-CPC-1247): fix bug in get vet by first name and last name** is correct for the naming. The changes look good, but the number of files modified seems quite large for a bug fix.

**Review by bluement — DISMISSED** [review]
much better and clearer coding for the bugfix, frontend looks good and pr is well made after the changes.

**Review by bluement — APPROVED** [review]
lots of my features deleted but apparently its what was meant to be done, so just a rework of my method, well done

**Review by Edwxd — APPROVED** [review]
A lot of changes but it was expected as we didn't want to have an end point for searching by names. Working with the front end only for the search query is better code overall. Good Job.

**Pull request merged**
