### PR TITLE
Feat/cstm cpc 901 delete pet from an owner

### PR DESCRIPTION
**Pull request by DisgruntledMensch**
JIRA: link to jira ticket
https://champlainsaintlambert.atlassian.net/browse/CPC-901
## Context:
Adding the ability to delete a pet from an owner using its ID, an having the change be displayed on the site
## Changes
Redid the deletePetByPetId function, its implementation on the gateway, created a JS func for it in ownderdetails and touched up the ownerDetails page to display the deleted pet.

## Before and After UI (Required for UI-impacting PRs)
**Before**
image

**After**

image

**After Deletion**

image

### CODE REVIEW

**Review by 1-emil — COMMENTED** [review]
why did you remove the buttons for edit and activate/deactivate pet? and why did you change the pet id promise to cache false? I would approve but scared it breaks my stuff

**Comment by DisgruntledMensch** [comment]
> why did you remove the buttons for edit and activate/deactivate pet? and why did you change the pet id promise to cache false? I would approve but scared it breaks my stuff

I didn't remove the buttons, what do you mean? I turned off caching for during troubleshooting, caching shouldn't be required for whatever you're doing and shouldn't have any effect on what you're doing.

**Review by Saimirz — APPROVED** [review]
Everything seems to be okay. I am not sure if you noticed or if it is already done, but i believe you are missing tests in the Customer Service Reactive. The tests in the API-Gateway are there though. Good stuff!

**Review by mattjulienn — APPROVED** [review]
I'm glad you finally got your delete feature to work !! Let's sort out that persistency problem next sprint, we've got this :)

**Pull request merged**
