### PR TITLE
feat/(CUST-CPC-1077): Update customer information on website

### PR DESCRIPTION
**Pull request by flyindonut**
JIRA: https://champlainsaintlambert.atlassian.net/browse/CPC-1077
## Context:
Created a v2 endpoint to update an owner's information and web page where the logged in customer can update their information.
## Changes
- Created the OwnerController class in the v2 folder of the API gateway
- Created the endpoint to update an owner's information in the Controller
- Created two controller integration tests to cover the implementation of the endpoint
- Added the mockserver depency in build.gradle
- Created the ProfileEdit page where customers can update their information on a pre-filled form. The pre-filled information is based on the logged in customer.
- Created the necessary files for the implementation of the ProfileEdit page (models, API calls, CSS)
## Before and After UI (Required for UI-impacting PRs)
image

### CODE REVIEW

**Review by NotZagreus — DISMISSED** [review]
Everything looks great! The changes are well-structured, tests are in place, and the user experience is implemented. The mockserver testing is good.

**Comment by DylanBrass** [comment]
My annotation was used correctly finally, thank you haha

**Review by Justin222993 — APPROVED** [review]
Everything looks good

**Review by AndrewBadIdea — APPROVED** [review]
This is perfect !

**Pull request merged**
