### PR TITLE
conf(VISE-CPC-183): change dockerfile to use openjdk 8-alpine

### PR DESCRIPTION
**Pull request by cjayneb**

### CODE REVIEW

**Review by cjayneb — COMMENTED** [review]
lgtm

**Comment by Funnyadd** [comment]
lgtm

**Review by Funnyadd — COMMENTED** [review]
lgtm

**Review by Funnyadd — APPROVED** [review]
lgtm

**Review by codingbeast666 — APPROVED** [review]
amazing. 11/10

**Pull request merged**
